[package]
name = "takdir-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
apalis = { workspace = true }
apalis-redis = { workspace = true }
takdir-core = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
redis = { workspace = true }
deadpool-postgres = { workspace = true }
deadpool-redis = { workspace = true }
